language: node_js

node_js: stable

cache:
  apt: true
  directories:
    - node_modules
before_install:
  - export TZ='Asia/Shanghai' # 更改时区
  - npm install hexo-cli -g
  - chmod +x ./build.sh  # 为shell文件添加可执行权限

install:
  - npm install

script:
  - hexo clean
  - hexo g

after_script:
  - ./build.sh

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/swust-xiaoj/swust-xiaoj.github.io.git