language: node_js  #设置语言

node_js: stable  #设置相应的版本

install:
  - npm install  #安装hexo及插件

script:
  - hexo clean  #清除
  - hexo g  #生成

after_script:
  - cd ./public
  - git init
  - git config user.name "swust-xiaoj"  #修改name
  - git config user.email "swustxiaojie@163.com"  #修改email
  - git add .
  - git commit -m "update site"
  - git push --force  "https://${travis}@${GH_REF}" master:master  #travis是在Travis中配置token的名称

branches:
  only:
    - master  #只监测master，可根据自己情况设置
env:
 global:
   - GH_REF: github.com/swust-xiaoj/tb.git  #设置GH_REF，注意更改yourname