# Blog info
blog_name: Sincerly
slogan: 我们泪流满面，步步回头，却只能向前走。
url: http://dearxiaojie.top/

# Set avatar (Absolute url and relative url)
avatar: /images/avatar.jpg

# Set favicon
favicon: /favicon.ico

# For seo
keywords: web,frontend,javascript,html,css,reactnative

home_nav:
  - name: Blog
    url: /archives/
    target_blank: false #不在新页面打开
  - name: Gmail
    url: mailto:hexy.xiaojie@gmail.com
    target_blank: true #在新页面打开
  - name: Github
    url: https://github.com/swust-xiaoj
    target_blank: true
  - name: Project
    url: /project/
    target_blank: true
  - name: Twitter
    url: https://twitter.com/dearxiaojie
    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: true # true|fase
  text: 盒子

search_slogan:
  isShow: true # true|fase
  text: nooooooooooooooo result ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 hexy.xiaojie@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: false
  btn_text: 支持一下
  tip: 扫一扫，支持
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: cd3bea7d045fc3fdc9952df80e48e5ec

# Comment service
disqus_shortname: xiaojie
# gitalk_shortname: xxx
# hypercomments_id: xxx
# gentie_key: xxx

#有言用户编号
#uyan_key:

# changyan_appid:
# changyan_appkey:

# gitment comment service
# gitment:
#     on: false  # true | false  这里开启
#     owner: # Your GitHub ID. Required.
#     repo: # The repository to store your comments. Make sure you're repo's owner. Required.
#     oauth: # An object contains your client ID and client secret. Required.
#         client_id: # GitHub client ID. Required.
#         client_secret: # GitHub client secret. Required.
#     id: # An optional string to identify your page. Default location.href.
#     title: # An optional title for your page, used as issue's title. Default document.title.
#     link: # An optional link for your page, used in issue's body. Default location.href.
#     desc: # An optional description for your page, used in issue's body. Default ''.
#     labels: # An optional array of labels your want to add when creating the issue. Default [].
#     theme: # An optional Gitment theme object. Default gitment.defaultTheme.
#     perPage: # An optional number to which comments will be paginated. Default 20.
#     maxCommentHeight: # An optional number to limit comments' max height, over which comments will be folded. Default 250.

# Valine comment system  https://valine.js.org
valine:
  enable: false # 如果使用valine，请设置改之为true
  appid:  # your leancloud application appid
  appkey:  # your leancloud application appkey
  notify: false # mail notifier , https://github.com/xCss/Valine/wiki
  verify: false # Verification code
  placeholder: Just go go # comment box placeholder
  avatar: mm # gravatar style
  guest_info: nick,mail,link # custom comment header
  pageSize: 10 # pagination size




# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "xiaojie，1993."
    - "喜欢睡懒觉，做饭."
    - "前端开发工程师，常用 HTML / CSS / JavaScript / react."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@paradise"
    text_value_url: https://github.com/swust-xiaoj
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@幼稚园的小班草丶"
    text_value_url: https://weibo.com/xiaojie0428
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "hexy.xiaojie"
    text_value_url: mailto:xiaojie6170@gmail.com
  - type: location
    icon: icon-location
    text_value: Beijing

link:
  - name: woodrat
    info: 记录下折腾和学习的过程
    url: http://woodrat.xyz/
    avatar: https://avatars1.githubusercontent.com/u/6253308?s=400&v=4
  - name: shine
    info: 生命不止，折腾不息!!!
    url: http://shinelee.ml/
    avatar: https://avatars2.githubusercontent.com/u/13914318?s=400&v=4
  - name: zengmaoyun
    info: 好记性不如烂笔头
    url: https://zengmaoyun.github.io/blog/
    avatar: https://zengmaoyun.github.io/blog/img/head.png
  - name: 未知账号
    info: 一个积极奋进的女汉子
    url: https://weizhizhanghao.github.io/
    avatar: https://avatars3.githubusercontent.com/u/16538127?s=400&v=4
  - name: medium
    info: Read write and share stories that matter
    url: https://medium.com/@xiaojie6170
    avatar: https://cdn-images-1.medium.com/fit/c/200/200/1*qKrtOtChWX7CmwYAn8cbZQ.jpeg
  - name: v2ex
    info: 创意工作者们的社区
    url: https://www.v2ex.com/
    avatar: https://www.v2ex.com/static/img/v2ex@2x.png

project:
  - type: personal
    name: paradise
    url: https://github.com/swust-xiaoj/paradise
    intro: blog source
